"""Snapshot tracking — record cron-generated base snapshots.

REQ-DELTA-01-11: snapshots table CRUD.
REQ-DELTA-01-12: On cron build completion, create snapshot row and mark old deltas merged.
"""

from __future__ import annotations

import hashlib
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from trading.db.session import connection

LOG = logging.getLogger(__name__)


def create_snapshot(
    snapshot_type: str,
    file_path: str,
    generated_at: datetime | None = None,
) -> int | None:
    """Record a new base snapshot generated by cron.

    REQ-DELTA-01-12: Creates snapshot row, marks old deltas as merged.

    Args:
        snapshot_type: 'macro', 'micro', or 'news'.
        file_path: Path to the generated .md file.
        generated_at: When the snapshot was generated (default: now).

    Returns:
        The new snapshot id, or None on failure.
    """
    generated_at = generated_at or datetime.now()

    # Compute content hash
    content_hash = _compute_file_hash(file_path)

    sql = """
        INSERT INTO snapshots (snapshot_type, generated_at, file_path, content_hash)
        VALUES (%s, %s, %s, %s)
        RETURNING id
    """
    try:
        with connection() as conn, conn.cursor() as cur:
            cur.execute(sql, (snapshot_type, generated_at, file_path, content_hash))
            row = cur.fetchone()
            if not row:
                return None
            new_id = row["id"]

            # Mark all previous un-merged deltas for this snapshot type as merged
            # Find the previous snapshot id for this type
            cur.execute(
                """
                SELECT id FROM snapshots
                WHERE snapshot_type = %s AND id < %s
                ORDER BY id DESC LIMIT 1
                """,
                (snapshot_type, new_id),
            )
            prev = cur.fetchone()
            if prev:
                cur.execute(
                    "UPDATE delta_events SET merged = true WHERE snapshot_id = %s AND merged = false",
                    (prev["id"],),
                )
                merged_count = cur.rowcount if hasattr(cur, "rowcount") else 0
                LOG.info(
                    "Snapshot %s created (id=%d), marked %d old deltas as merged",
                    snapshot_type, new_id, merged_count,
                )

            return new_id
    except Exception:
        LOG.exception("Failed to create snapshot: type=%s, path=%s", snapshot_type, file_path)
        return None


def get_latest_snapshot(snapshot_type: str) -> dict[str, Any] | None:
    """Get the most recent snapshot for a given type.

    Returns dict with id, snapshot_type, generated_at, file_path, content_hash, delta_count.
    """
    sql = """
        SELECT id, snapshot_type, generated_at, file_path, content_hash, delta_count, created_at
        FROM snapshots
        WHERE snapshot_type = %s
        ORDER BY id DESC
        LIMIT 1
    """
    with connection() as conn, conn.cursor() as cur:
        cur.execute(sql, (snapshot_type,))
        return cur.fetchone()


def _compute_file_hash(file_path: str) -> str:
    """Compute SHA-256 hash of file content. Returns empty string if file missing."""
    try:
        path = Path(file_path)
        if path.exists():
            return hashlib.sha256(path.read_bytes()).hexdigest()
    except Exception:
        LOG.warning("Cannot compute hash for %s", file_path)
    return ""
