"""SPEC-TRADING-040 M1a/1b (REQ-040-1a/1b) — moderate profit-taking EV gate.

The SPEC forbids GUESSING a profit-take threshold and forbids applying one that
LOWERS expected value (the narrow-take-profit trap that SPEC-037 surfaced: a
tight take has a high win rate but negative expectancy). Before any moderate
profit-take layer is added BELOW the existing take rule, the candidate must pass
an expected-value NON-DECREASE gate against the deterministic exit backtest
(``backtest.exit_sweep``) — and only a STRICT improvement justifies adding a new
layer at all.

This is the code form of the principle. The decision (adopt or reject) is driven
entirely by the backtest numbers, not hardcoded. As of the 2026-06-03 10y
KOSPI200 backtest the gate REJECTS adding a moderate take: expectancy is
maximised at the WIDE take (3.0xATR, the existing live config) and falls
monotonically as the take tightens (2.0x -> +0.06, 1.5x -> -0.10). The first
round-trips are therefore generated by RISK-motivated TRIMs (concentration cap
+ stagnation rotation, EV-exempt, see ADR-1) and the repeat-buy block, NOT by
EV-harming premature profit-taking.

@MX:SPEC: SPEC-TRADING-040
"""

from __future__ import annotations

from dataclasses import dataclass

from trading.backtest.exit_sweep import SweepMetrics

# Honesty footer (REQ-040-5b) — tone-matched to edge.scorecard.limitations_footer.
EV_GATE_LIMITATIONS = (
    "EV gate validates the deterministic EXIT rule only; the LLM entry edge is "
    "NOT backtestable (look-ahead). A passing gate means a take threshold does "
    "not reduce per-trade expectancy on historical KOSPI200 — it is NOT evidence "
    "the live strategy is profitable. Confirm entry edge via forward paper "
    "edge-report. Trims (concentration / stagnation) are risk-motivated and "
    "EXEMPT from this gate (ADR-1); only profit-taking is gated."
)


@dataclass(frozen=True)
class ProfitTakeDecision:
    """Outcome of the EV gate for adding a moderate profit-take layer."""

    adopt: bool
    best_take_atr_mult: float | None
    current_take_atr_mult: float
    best_expectancy: float | None
    current_expectancy: float | None
    rationale: str


def _expectancy_for(results: list[SweepMetrics], take_atr_mult: float) -> float | None:
    """Best expectancy among sweep rows at the given take multiplier (or None)."""
    matching = [m.expectancy for m in results if m.params.take_atr_mult == take_atr_mult]
    return max(matching) if matching else None


# @MX:NOTE: SPEC-TRADING-040 M1b — the EV non-decrease gate. Adopt a moderate
# take layer ONLY when the best-expectancy take strictly beats the current take.
# Data-driven: with the real backtest (best EV at the wide take) it returns
# adopt=False, so no EV-harming profit-taking is forced.
def select_profit_take_threshold(
    results: list[SweepMetrics],
    *,
    current_take_atr_mult: float,
) -> ProfitTakeDecision:
    """Decide whether to ADD a (moderate) profit-take layer (REQ-040-1a/1b).

    Picks the take multiplier with the highest backtest expectancy. Adopts it
    only if it is a DIFFERENT take from the current one AND strictly improves
    expectancy (EV non-decrease, with a strict-improvement requirement to justify
    the change). Otherwise the existing (wider) take is kept and no moderate take
    is added — the SPEC's contingency when profit-taking is EV-harming.
    """
    if not results:
        return ProfitTakeDecision(
            adopt=False,
            best_take_atr_mult=None,
            current_take_atr_mult=current_take_atr_mult,
            best_expectancy=None,
            current_expectancy=None,
            rationale="no backtest results — cannot adopt any profit-take. "
            + EV_GATE_LIMITATIONS,
        )

    best = max(results, key=lambda m: m.expectancy)
    best_take = best.params.take_atr_mult
    best_exp = best.expectancy
    current_exp = _expectancy_for(results, current_take_atr_mult)

    # Adopt only a DIFFERENT take that STRICTLY improves expectancy.
    adopt = (
        best_take != current_take_atr_mult
        and current_exp is not None
        and best_exp > current_exp
    )

    if adopt:
        rationale = (
            f"adopt take_atr_mult={best_take} (expectancy {best_exp:.3f}%) over "
            f"current {current_take_atr_mult} ({current_exp:.3f}%) — strict EV "
            f"improvement. " + EV_GATE_LIMITATIONS
        )
    else:
        cur_str = "n/a" if current_exp is None else f"{current_exp:.3f}%"
        rationale = (
            f"REJECT moderate profit-taking — best expectancy is at "
            f"take_atr_mult={best_take} ({best_exp:.3f}%); a tighter take does not "
            f"beat the current {current_take_atr_mult} ({cur_str}). Adding a "
            f"moderate take would LOWER expectancy (narrow-take trap). Keep the "
            f"wide take; generate first round-trips via risk-motivated trims. "
            + EV_GATE_LIMITATIONS
        )

    return ProfitTakeDecision(
        adopt=adopt,
        best_take_atr_mult=best_take,
        current_take_atr_mult=current_take_atr_mult,
        best_expectancy=best_exp,
        current_expectancy=current_exp,
        rationale=rationale,
    )
